import { mkdir, readFile, writeFile } from 'node:fs/promises';
import { join } from 'node:path';

const siteUrl = (process.env.PUBLIC_SITE_URL || process.env.VITE_SITE_URL || 'http://localhost:5173').replace(/\/$/, '');
const realMaterials = [
  ['aluminium','Aluminium'],['black-battery','Black Battery'],['brass','Brass'],['cardboard','Cardboard'],['chimney-scrap','Chimney'],['copper','Copper'],['fan-copper-wiring','Fan Copper Wiring'],['glass','Glass'],['inverter-scrap','Inverter Scrap'],['iron','Iron'],['iron-cooler','Iron Cooler'],['lcd-monitor','LCD Monitor'],['lcd-tv','LCD TV'],['light-iron','Light Iron'],['magazine','Magazine'],['metal-e-waste','Metal E-Waste'],['motor-copper-wiring','Motor Copper Wiring'],['newspaper','Newspaper'],['office-paper','Office Paper'],['old-books','Old Books'],['plastic','Plastic'],['plastic-cooler','Plastic Cooler'],['plastic-e-waste','Plastic E-Waste'],['printer','Printer'],['ro-scrap','RO Scrap'],['stabilizer-copper','Stabilizer Copper'],['steel','Steel'],['tin-light-iron','Tin Light Iron'],['white-battery','White Battery'],
];
const staticPages = [['scrap-prices',"Today's Scrap Prices in Delhi NCR",'Compare published indicative local scrap buying rates, freshness and stored trends.'],['about','About ScrapRate','Transparent daily scrap price tracking and historical data.'],['contact','Contact ScrapRate','Contact information for data questions and corrections.'],['methodology','Price Methodology','How ScrapRate calculates indicative rates from active source observations.'],['sources','Price Sources','Source attribution and transparency for ScrapRate price observations.'],['disclaimer','Price Disclaimer','Important limitations of indicative scrap rates.'],['privacy','Privacy Notice','How ScrapRate handles analytics, logs and contact information.'],['terms','Terms of Use','Conservative terms for using ScrapRate price information.']];
const template = await readFile('dist/index.html','utf8');
function render(path,title,description,h1){
  const canonical = `${siteUrl}/${path}`;
  return template.replace(/<title>.*?<\/title>/s,`<title>${title} | ScrapRate</title>`).replace(/<meta name="description" content="[^"]*"\s*\/>/,`<meta name="description" content="${description}" />`).replace('</head>',`<link rel="canonical" href="${canonical}" /><meta property="og:title" content="${title} | ScrapRate" /><meta property="og:description" content="${description}" /></head>`).replace('<div id="root"></div>',`<div id="root"><main><h1>${h1}</h1><p>${description}</p><p>Prices are indicative and may vary by grade, quantity, location and inspection.</p></main></div>`);
}
await writeFile(join('dist','index.html'), render('', "Today's Scrap Prices in Delhi NCR", 'Track published scrap buying rates, historical trends and recycling values.', "Today's Scrap Prices in Delhi NCR"));
for (const [path,title,description] of staticPages){const dir=join('dist',path);await mkdir(dir,{recursive:true});await writeFile(join(dir,'index.html'),render(path,title,description,title));}
for (const [slug,name] of realMaterials){const path=`scrap-price/${slug}`;const title=`${name} Scrap Price in Delhi NCR Today`;const description=`View the latest published indicative ${name.toLowerCase()} scrap buying rate, source freshness and stored price history for Delhi NCR.`;const dir=join('dist','scrap-price',slug);await mkdir(dir,{recursive:true});await writeFile(join(dir,'index.html'),render(path,title,description,title));}
const notFound = template.replace(/<meta name="robots" content="[^"]*"\s*\/>/, '<meta name="robots" content="noindex, nofollow" />').replace(/<title>.*?<\/title>/s,'<title>Page Not Found | ScrapRate</title>').replace('<div id="root"></div>','<div id="root"><main><h1>Page not found</h1><p>The requested ScrapRate page does not exist.</p></main></div>');
await writeFile(join('dist','404.html'),notFound);
console.log(`Prerendered ${staticPages.length + realMaterials.length + 1} public routes for ${siteUrl}`);
