import { useEffect, useState } from 'react';
import { Activity, ArrowLeft, Eye, KeyRound, Monitor, RefreshCw, Users } from 'lucide-react';
import { analyticsAdminApi } from '../services/api';
import './admin-prices.css'; import './analytics.css';
const number=value=>Number(value||0).toLocaleString('en-IN');
export default function AdminAnalytics(){const [key,setKey]=useState(()=>sessionStorage.getItem('scraprate_admin_key')||''),[days,setDays]=useState(30),[data,setData]=useState(null),[error,setError]=useState(''),[loading,setLoading]=useState(false);
 const load=async()=>{if(!key){setError('Enter the admin analytics key.');return}setLoading(true);setError('');try{sessionStorage.setItem('scraprate_admin_key',key);setData(await analyticsAdminApi.summary(days,key));}catch(e){setError(e.message);setData(null)}finally{setLoading(false)}}; useEffect(()=>{if(key)load()},[days]);
 return <div className="admin-page"><header className="admin-header"><div className="admin-shell"><a className="admin-brand" href="/">ScrapRate <small>ADMIN ANALYTICS</small></a><a className="admin-back" href="/admin/prices"><ArrowLeft size={17}/> Price admin</a></div></header><main className="admin-main admin-shell"><section className="admin-intro"><div><span className="admin-eyebrow">PRIVACY-SAFE TRAFFIC</span><h1>Website analytics</h1><p>Anonymous visits and product interactions. Raw IP addresses and personal identities are not stored.</p></div><div className="analytics-auth"><KeyRound size={17}/><input type="password" aria-label="Admin analytics key" placeholder="Admin key" value={key} onChange={e=>setKey(e.target.value)}/><button onClick={load}>{loading?<RefreshCw className="spin" size={16}/>:<Activity size={16}/>} Load</button></div></section>{error&&<div className="admin-alert error">{error}</div>}{data&&<><div className="analytics-toolbar"><label>Period <select value={days} onChange={e=>setDays(Number(e.target.value))}><option value="7">7 days</option><option value="30">30 days</option><option value="90">90 days</option></select></label><button onClick={load} aria-label="Refresh analytics"><RefreshCw size={16}/></button></div><section className="metric-grid"><Metric icon={Eye} label="Page views" value={data.page_views}/><Metric icon={Users} label="Unique visitors" value={data.unique_visitors}/><Metric icon={Activity} label="Sessions" value={data.sessions}/><Metric icon={Monitor} label="Today's views" value={data.today_page_views}/></section><section className="analytics-grid"><List title="Top pages" rows={data.top_pages}/><List title="Referrers" rows={data.top_referrers}/><List title="Devices" rows={data.devices}/><List title="Browsers" rows={data.browsers}/></section><section className="recent-card"><div className="admin-section-heading"><div><span>RECENT PAGE VIEWS</span><h2>Anonymous visit activity</h2></div></div><div className="admin-table-wrap"><table><thead><tr><th>Time</th><th>Anonymous visitor</th><th>Page</th><th>Referrer</th><th>Device</th><th>Browser / OS</th></tr></thead><tbody>{data.recent_visits.map((row,index)=><tr key={`${row.time}-${index}`}><td>{new Date(row.time).toLocaleString()}</td><td><code>{row.visitor}</code></td><td>{row.path}</td><td>{row.referrer||'Direct'}</td><td>{row.device}</td><td>{row.browser} / {row.operating_system}</td></tr>)}</tbody></table></div></section></>}</main></div>}
function Metric({icon:Icon,label,value}){return <article><Icon/><span>{label}</span><strong>{number(value)}</strong></article>}
function List({title,rows}){return <article className="analytics-list"><h2>{title}</h2>{rows.length?rows.map(row=><div key={row.name}><span>{row.name}</span><b>{number(row.count)}</b></div>):<p>No data yet</p>}</article>}
