import React, { useEffect, useState } from 'react';
import { AlertTriangle, ArrowLeft, Database, LoaderCircle, Play, RefreshCw, ShieldAlert } from 'lucide-react';
import { dataSourceApi } from '../services/api';
import './admin-prices.css'; import './data-sources.css';

const when = value => value ? new Date(value).toLocaleString() : 'Never';
export default function AdminDataSources() {
  const [rows,setRows]=useState([]),[loading,setLoading]=useState(true),[running,setRunning]=useState(null),[error,setError]=useState('');
  const load=()=>{setLoading(true);setError('');dataSourceApi.list().then(setRows).catch(e=>setError(e.message)).finally(()=>setLoading(false));}; useEffect(load,[]);
  const run=async row=>{setRunning(row.id);setError('');try{await dataSourceApi.run(row.id);load();}catch(e){setError(e.message);}finally{setRunning(null);}};
  return <div className="admin-page"><header className="admin-header"><div className="admin-shell"><a className="admin-brand" href="/">ScrapRate <small>MARKET INTELLIGENCE</small></a><a className="admin-back" href="/admin/prices"><ArrowLeft size={17}/> Price admin</a></div></header><main className="admin-main admin-shell">
    <section className="admin-intro"><div><span className="admin-eyebrow">INGESTION HEALTH</span><h1>Automated data sources</h1><p>Monitor adapter availability, source quality, and the latest audited ingestion attempt.</p></div><div className="security-note"><ShieldAlert size={19}/><span><strong>No secrets stored here</strong>Credentials belong in environment variables or a managed secret store.</span></div></section>
    {error&&<div className="admin-alert error"><AlertTriangle size={17}/>{error}</div>}
    <section className="recent-card"><div className="admin-section-heading source-heading"><div><span>REGISTERED SOURCES</span><h2>Source health</h2></div><button className="icon-button" onClick={load} aria-label="Refresh sources"><RefreshCw size={18}/></button></div>
    {loading?<div className="admin-loading"><LoaderCircle className="spin"/>Loading sources…</div>:!rows.length?<div className="admin-empty"><Database/><strong>No price sources</strong></div>:<div className="admin-table-wrap"><table><thead><tr><th>Source</th><th>Quality</th><th>Adapter</th><th>Last success</th><th>Last attempt</th><th>Latest run</th><th>Received / inserted</th><th>Action</th></tr></thead><tbody>{rows.map(row=><tr key={row.id}><td><strong>{row.name}</strong><small>{row.source_type} · {row.city||'All cities'}</small></td><td><span className={`source-state ${row.is_active?'active':'inactive'}`}>{row.is_active?'Active':'Inactive'}</span><small>{row.is_verified?'Verified':'Unverified'} · Trust {row.trust_score}</small></td><td><strong>{row.adapter_name||'Not configured'}</strong><small>{row.adapter_registered?'Registered':row.adapter_name?'Unsupported':'Manual source'}</small></td><td>{when(row.last_success_at)}</td><td>{when(row.last_attempt_at)}</td><td><span className={`run-state ${row.latest_run?.status||'none'}`}>{row.latest_run?.status||'No runs'}</span>{row.last_error&&<small className="error-text">{row.last_error}</small>}</td><td>{row.latest_run?`${row.latest_run.records_received} / ${row.latest_run.records_inserted}`:'—'}</td><td><button className="run-button" disabled={!row.adapter_registered||!row.adapter_enabled||!row.is_active||running===row.id} onClick={()=>run(row)} title={!row.adapter_registered?'No registered adapter available':'Run source now'}>{running===row.id?<LoaderCircle className="spin" size={15}/>:<Play size={15}/>}Run</button></td></tr>)}</tbody></table></div>}</section>
  </main></div>;
}
