import { useEffect, useMemo, useState } from 'react';
import PriceChart from '../components/PriceChart';
import ConfidenceBadge from '../components/ConfidenceBadge';
import { api } from '../services/api';
import { setSeo } from './seo';
import { LaunchHeader } from './ScrapPricesPage';
import { PublicFooter } from './StaticPage';
import NotFoundPage from './NotFoundPage';
import { trackEvent } from '../analytics';
import './public-pages.css';
const money=v=>Number(v).toLocaleString('en-IN',{maximumFractionDigits:2});
export default function MaterialPricePage({slug}) { const [data,setData]=useState(null); const [error,setError]=useState(''); const [days,setDays]=useState(30); const [weight,setWeight]=useState(10);
 useEffect(()=>{api.detail(slug,'delhi').then(value=>{setData(value);trackEvent('material_viewed',{material_slug:slug});const canonical=`${location.origin}/scrap-price/${slug}`;setSeo({title:value.seo_title||`${value.material} Scrap Price Today in Delhi NCR | ScrapRate`,description:value.seo_description||`View the current indicative ${value.material.toLowerCase()} scrap price, market range, source freshness and stored history for Delhi NCR.`,canonical,schema:{'@context':'https://schema.org','@type':'WebPage',name:`${value.material} scrap price today`,url:canonical,breadcrumb:{'@type':'BreadcrumbList',itemListElement:[{'@type':'ListItem',position:1,name:'Scrap Prices',item:`${location.origin}/scrap-prices`},{'@type':'ListItem',position:2,name:value.material,item:canonical}]}}});}).catch(e=>setError(e.status===404?'not-found':'unavailable'));},[slug]);
 const history=useMemo(()=>data?.history?.slice(-days)||[],[data,days]); if(error==='not-found')return <NotFoundPage/>; if(error)return <><LaunchHeader/><main className="public-page"><div className="state-card error-state"><strong>Price data is temporarily unavailable</strong><span>Please try again later. No stored rate has been altered.</span></div></main></>; if(!data)return <><LaunchHeader/><main className="public-page"><div className="loading-grid"><div className="loader"/>Loading material price…</div></main></>;
 const span=data.history.length?Math.floor((new Date(data.history.at(-1).date)-new Date(data.history[0].date))/86400000)+1:0; const periods=[7,30,90,180,365].filter(d=>span>=d);
 return <><LaunchHeader/><main className="public-page"><section className="detail-hero"><span>{data.category} · {data.city}</span><h1>{data.material} Scrap Price in Delhi NCR Today</h1><div className="detail-price">₹{money(data.indicative_price)} <small>/ {data.unit}</small></div><div className="detail-badges"><ConfidenceBadge level={data.confidence}/><b className={`data-type-badge ${data.data_type}`}>{data.data_type}</b><span>{data.freshness_label}</span></div><p>{data.description}</p></section>
 <section className="chart-panel"><header><div><h2>Stored price history</h2><p>Only observations stored in ScrapRate’s database are shown.</p></div><div className="periods">{periods.map(d=><button aria-pressed={days===d} className={days===d?'active':''} onClick={()=>{setDays(d);trackEvent('chart_period_changed',{material_slug:slug,days:d})}} key={d}>{d<90?`${d}D`:d===90?'3M':d===180?'6M':'1Y'}</button>)}</div></header><PriceChart data={history} unit={data.unit}/><table className="chart-fallback"><caption>Recent stored prices</caption><thead><tr><th>Date</th><th>Indicative price</th></tr></thead><tbody>{history.slice(-5).map(point=><tr key={point.date}><td>{point.date}</td><td>₹{money(point.price)}/{data.unit}</td></tr>)}</tbody></table></section>
 <section className="detail-stat-grid"><div><span>Market low</span><b>₹{money(data.low)}</b></div><div><span>Market high</span><b>₹{money(data.high)}</b></div><div><span>Median</span><b>₹{money(data.median)}</b></div><div><span>Active sources</span><b>{data.source_count}</b></div></section>
 <section className="detail-stat-grid period-stat-grid">{data.statistics?.seven_day&&<div><span>7-day change</span><b>{Number(data.statistics.seven_day.change)>=0?'+':''}₹{money(data.statistics.seven_day.change)} ({Number(data.statistics.seven_day.change_percent).toFixed(2)}%)</b></div>}{data.statistics?.thirty_day&&<div><span>30-day change</span><b>{Number(data.statistics.thirty_day.change)>=0?'+':''}₹{money(data.statistics.thirty_day.change)} ({Number(data.statistics.thirty_day.change_percent).toFixed(2)}%)</b></div>}<div><span>Stored observations</span><b>{data.statistics?.available_observations||0}</b></div><div><span>Period average</span><b>{data.statistics?.average?`₹${money(data.statistics.average)}`:'Unavailable'}</b></div></section>
 <section className="source-panel"><h2>Source transparency</h2>{data.source_details?.map(source=><article key={source.name}><b>{source.name}</b><span>{source.type?.replaceAll('_',' ')} · trust {source.trust_score}/100</span>{source.url&&<a href={source.url} target="_blank" rel="noreferrer">Source reference</a>}</article>)}<p>Indicative rates are not guaranteed buyer offers. Quality, quantity and inspection affect the final price.</p></section>
 <section className="material-calculator"><h2>Calculate {data.material} scrap value</h2><label htmlFor="material-weight">Weight in kilograms</label><input id="material-weight" type="number" min="0.01" step="0.5" value={weight} onChange={e=>{setWeight(e.target.value);trackEvent('calculator_used',{material_slug:slug})}}/><strong>{Number(weight)>0?`₹${money(Number(weight)*data.indicative_price)}`:'Enter a valid weight'}</strong><p>Indicative estimate only. Actual buyer prices vary after inspection.</p></section>
 <section className="content-grid"><article><h2>About {data.material}</h2><p>{data.description || `${data.material} is tracked as a recyclable material in ScrapRate’s Delhi NCR price directory.`}</p></article><article><h2>What affects the price?</h2><p>Grade, purity, contamination, quantity, pickup location, transport cost, inspection and buyer demand can change the final buying rate.</p></article><article><h2>Source methodology</h2><p>ScrapRate groups active local observations by date, prioritizes real data, and calculates an indicative rate using source trust and median pricing. Raw observations remain preserved.</p></article><article><h2>Frequently asked question</h2><h3>Is this a guaranteed buying rate?</h3><p>No. It is an indicative published rate and not a binding offer.</p></article></section>
 <a className="btn btn-primary detail-cta" href="/scrap-prices">View related scrap materials</a></main><PublicFooter/></> }
