import { useEffect } from 'react';
import { LaunchHeader } from './ScrapPricesPage';
import { setSeo } from './seo';
import './public-pages.css';

const pages = {
  methodology: { title: 'Price Methodology', intro: 'How ScrapRate turns published and submitted observations into transparent indicative scrap rates.', sections: [['How prices are calculated', 'ScrapRate groups active local-scrap observations by material, city and date. Real observations take priority over demo data. The indicative rate uses an explainable median and trust-weighted average while preserving every raw observation.'], ['Freshness and movement', 'Freshness is based on the observation date. Daily movement compares the latest indicative rate with the nearest previous available date, never an invented missing day.'], ['What affects a final offer', 'Grade, purity, contamination, quantity, location, transport, inspection and current buyer demand may all change the amount offered.']] },
  sources: { title: 'Price Data', intro: 'ScrapRate tracks published and submitted scrap buying-rate observations for price-discovery purposes.', sections: [['How observations are used', 'Eligible observations are normalized by material, city and date before contributing to an indicative ScrapRate price. Source administration and quality controls are maintained internally.'], ['Independent data collection', 'Published observations are tracked independently for factual market-reference purposes. Inclusion does not imply partnership, endorsement or ownership.'], ['No copied branding', 'Third-party branding, descriptions and photography are not republished as ScrapRate assets.']] },
  disclaimer: { title: 'Price Disclaimer', intro: 'ScrapRate provides informational, indicative scrap price intelligence—not guaranteed buying offers.', sections: [['Indicative information', 'Displayed prices may differ from an actual dealer quote. The final price depends on grade, purity, quantity, location, transport, inspection, market demand and buyer requirements.'], ['Availability', 'A stale or unavailable source may delay an update. The latest known observation remains labelled with its date and freshness rather than being silently replaced or fabricated.'], ['No transaction relationship', 'Using ScrapRate does not create a purchase, sale, brokerage or advisory relationship. Verify commercial terms directly with the relevant buyer or seller.']] },
  about: { title: 'About ScrapRate', intro: 'ScrapRate helps users understand scrap pricing through transparent daily rate tracking and historical data.', sections: [['Our purpose', 'Scrap pricing is fragmented and can be difficult to compare. ScrapRate organizes published observations, source context and stored trends into a clearer research experience.'], ['Our approach', 'We distinguish real observations from development data, disclose freshness and sources, and avoid presenting indicative calculations as official rates.']] },
  contact: { title: 'Contact ScrapRate', intro: 'Questions about data, corrections, partnerships or this website can be sent to the configured business contact.', sections: [['Contact details', `Email: ${import.meta.env.VITE_CONTACT_EMAIL || 'Contact email will be published before launch.'}`], ['Price corrections', 'When reporting a possible error, include the material, city, displayed date and the source reference. Do not send sensitive personal or payment information.']] },
  privacy: { title: 'Privacy Notice', intro: 'This notice explains the limited information ScrapRate may process when you use the website.', sections: [['Website and server logs', 'Hosting providers may record IP address, browser type, requested page, timestamps and diagnostic information for security and reliability.'], ['Analytics', 'Privacy-conscious analytics may be enabled through configuration. When enabled, it measures page and feature usage without sending price-source database records. No analytics script is loaded when no measurement ID is configured.'], ['Contact information', 'If you contact ScrapRate, the information you submit is used to respond and maintain relevant records.'], ['Cookies and third parties', 'The application does not require advertising cookies. Configured analytics or infrastructure providers may use limited storage according to their own terms.']] },
  terms: { title: 'Terms of Use', intro: 'These basic terms apply to the informational ScrapRate website.', sections: [['Permitted use', 'You may use the public pages for lawful personal or business research. Do not interfere with the service, bypass controls or misrepresent ScrapRate data as guaranteed or official pricing.'], ['Data and availability', 'Price information is indicative and may be incomplete, delayed or unavailable. ScrapRate does not guarantee accuracy, uninterrupted availability or a particular transaction outcome.'], ['Third-party sources', 'Source references remain the responsibility of their respective publishers. Attribution does not imply partnership or endorsement.'], ['Changes', 'Features, data coverage and these terms may change as the service develops. Material changes should be reflected by an updated publication date.']] },
};
export default function StaticPage({ page }) { const content=pages[page]; useEffect(()=>{setSeo({title:`${content.title} | ScrapRate`,description:content.intro,canonical:`${location.origin}/${page}`});},[page]); return <><LaunchHeader/><main className="public-page text-page"><p className="eyebrow">ScrapRate</p><h1>{content.title}</h1><p className="text-page__intro">{content.intro}</p>{content.sections.map(([heading,text])=><section key={heading}><h2>{heading}</h2><p>{text}</p></section>)}<p className="text-page__updated">Last updated: 23 August 2026</p></main><PublicFooter/></> }
export function PublicFooter(){return <footer className="launch-footer"><div><strong>Prices</strong><a href="/scrap-prices">Scrap Prices</a><a href="/scrap-price/copper">Copper</a><a href="/scrap-price/aluminium">Aluminium</a><a href="/scrap-price/brass">Brass</a><a href="/scrap-price/iron">Iron</a><a href="/scrap-price/cardboard">Cardboard</a></div><div><strong>Company</strong><a href="/about">About</a><a href="/methodology">Methodology</a><a href="/sources">Sources</a><a href="/contact">Contact</a></div><div><strong>Legal</strong><a href="/disclaimer">Disclaimer</a><a href="/privacy">Privacy</a><a href="/terms">Terms</a></div><p>ScrapRate · Daily scrap prices. Clear trends. Better decisions.</p></footer>}
